apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkaclusters.scalablecomputing.roperator.com
spec:
  group: scalablecomputing.roperator.com
  names:
    kind: KafkaCluster
    plural: kafkaclusters
    singular: kafkacluster
    shortNames:
      - kfc
  scope: Namespaced
  subresources:
    status:
      type: object
      properties:
        status:
          type: string
        brokerCount:
          type: integer
        zookeeperStatus:
          type: string
        brokerStatus:
          type: string
  versions:
    - name: v1alpha1
      storage: true
      served: true
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            brokerCount:
              type: integer
            zkServiceName:
              type: string
            kfServiceName:
              type: string
  additionalPrinterColumns:
    - name: Status
      type: string
      description: The status of the KafkaCluster
      JSONPath: .status.status
    - name: Zookeeper
      type: string
      description: The status of zookeer instance in the cluster
      JSONPath: .status.zookeeperStatus
    - name: Brokers
      type: integer
      description: The amount of broker instances in the cluster
      JSONPath: .spec.brokerCount
    - name: Broker status
      type: string
      description: The status of the broker instances in the cluster
      JSONPath: .status.brokerStatus