apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: sc
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    protocol: TCP
    port: 8080
  - name: web-ui2
    protocol: TCP
    port: 4040
    targetPort: 4040
  - name: master
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: master-rest
    protocol: TCP
    port: 6066
    targetPort: 6066
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-remote
  namespace: sc
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: web-ui2
    protocol: TCP
    port: 4040
    targetPort: 4040
    nodePort: 30040
  - name: master
    protocol: TCP
    port: 7077
    targetPort: 7077
    nodePort: 30077
  - name: master-rest
    protocol: TCP
    port: 6066
    targetPort: 6066
    nodePort: 30066
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: spark-client
  namespace: sc
spec:
  selector:
    app: spark-client
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: sc
  labels:
    app: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        resources:
          limits: 
            cpu: "1"
          requests:
            cpu: "1"
        image: soelmanm/scalablecomputing:spark-master #bde2020/spark-master:2.4.5-hadoop2.7
        imagePullPolicy: Always
        ports:
        - containerPort: 4040
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 6066
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: sc
  labels:
    app: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        resources:
          limits: 
            cpu: "3"
          requests:
            cpu: "2"
        image: bde2020/spark-worker:2.4.5-hadoop2.7
        imagePullPolicy: Always
        ports:
        - containerPort: 4041
        - containerPort: 8081
