apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: soelmanm/scalablecomputing:api
        imagePullPolicy: Always
        env: 
        - name: CASSANDRA_SEEDS
          value: cassandra-service
        - name: CASSANDRA_PORT
          value: "9042"
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "125m"
            memory: 64Mi