apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-service
  name: cassandra-service
  namespace: sc
spec:
  clusterIP: None
  ports:
  - name: cql
    port: 9042
    targetPort: 9042
  selector:
    app: cassandra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-service-external
  name: cassandra-service-external
  namespace: sc
spec:
  type: NodePort
  ports:
  - name: cql
    port: 9042
    targetPort: 9042
    nodePort: 30042
  selector:
    app: cassandra