apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    protocol: TCP
    port: 8080
  - name: web-ui-program1
    protocol: TCP
    port: 4040
    targetPort: 4040
  - name: web-ui-program2
    protocol: TCP
    port: 4041
    targetPort: 4041
  - name: web-ui-program3
    protocol: TCP
    port: 4042
    targetPort: 4042
  - name: web-ui-program4
    protocol: TCP
    port: 4043
    targetPort: 4043
  - name: web-ui-program5
    protocol: TCP
    port: 4044
    targetPort: 4044
  - name: web-ui-program6
    protocol: TCP
    port: 4045
    targetPort: 4045
  - name: master
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: master-rest
    protocol: TCP
    port: 6066
    targetPort: 6066
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-remote
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: web-program1
    protocol: TCP
    port: 4040
    targetPort: 4040
  - name: web-ui-program2
    protocol: TCP
    port: 4041
    targetPort: 4041
  - name: web-ui-program3
    protocol: TCP
    port: 4042
    targetPort: 4042
  - name: web-ui-program4
    protocol: TCP
    port: 4043
    targetPort: 4043
  - name: web-ui-program5
    protocol: TCP
    port: 4044
    targetPort: 4044
  - name: web-ui-program6
    protocol: TCP
    port: 4045
    targetPort: 4045
  - name: master
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: master-rest
    protocol: TCP
    port: 6066
    targetPort: 6066
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  externalTrafficPolicy: Cluster
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spark-client
spec:
  selector:
    app: spark-client
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        resources:
          limits: 
            cpu: "2"
          requests:
            cpu: "1"
        image: bde2020/spark-master:2.4.5-hadoop2.7
        imagePullPolicy: Always
        ports:
        - containerPort: 4040
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 6066
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  replicas: 6
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        resources:
          limits: 
            cpu: "3"
          requests:
            cpu: "1"
        image: bde2020/spark-worker:2.4.5-hadoop2.7
        imagePullPolicy: Always
        ports:
        - containerPort: 4041
        - containerPort: 8081
