---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-service
spec:
  type: ClusterIP 
  selector:
    component: kafka-1
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-service
spec:
  type: ClusterIP 
  selector:
    component: kafka-2
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3-service
spec:
  type: ClusterIP 
  selector:
    component: kafka-3
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092   
--- 
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    broker: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092