kubectl exec -it $(kubectl get pod -l "app=spark-master" -o jsonpath='{.items[0].metadata.name}') -- bash ./spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5,org.apache.spark:spark-streaming_2.11:2.4.5,org.apache.spark:spark-sql_2.11:2.4.5,org.apache.spark:spark-streaming-kafka-0-10_2.11:2.4.5,com.datastax.spark:spark-cassandra-connector_2.11:2.4.3,org.apache.kafka:kafka_2.11:2.4.0,org.apache.kafka:kafka-streams-scala_2.11:2.4.0 --class org.scalablecomputing.spark.streamingaverager.Main --master spark://spark-master:7077 --deploy-mode client --conf spark.app.name=streaming-averager --conf spark.driver.host=spark-master --conf spark.cores.max=3 --num-executors 3 --executor-cores 1 --supervise /streamingaverager.jar &
sleep 1m

kubectl exec -it $(kubectl get pod -l "app=spark-master" -o jsonpath='{.items[0].metadata.name}') -- bash ./spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5,org.apache.spark:spark-streaming_2.11:2.4.5,org.apache.spark:spark-sql_2.11:2.4.5,org.apache.spark:spark-streaming-kafka-0-10_2.11:2.4.5,com.datastax.spark:spark-cassandra-connector_2.11:2.4.3,org.apache.kafka:kafka_2.11:2.4.0,org.apache.kafka:kafka-streams-scala_2.11:2.4.0 --class org.scalablecomputing.spark.batchjobsaverager.Main --master spark://spark-master:7077 --deploy-mode client --conf spark.app.name=batch-averager-daily --conf spark.driver.host=spark-master --conf spark.cores.max=3 --num-executors 3 --executor-cores 1 --supervise /batchjobsaverager.jar daily &
#sleep 1m
#kubectl exec -it $(kubectl get pod -l "app=spark-master" -o jsonpath='{.items[0].metadata.name}') -- bash ./spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5,org.apache.spark:spark-streaming_2.11:2.4.5,org.apache.spark:spark-sql_2.11:2.4.5,org.apache.spark:spark-streaming-kafka-0-10_2.11:2.4.5,com.datastax.spark:spark-cassandra-connector_2.11:2.4.3,org.apache.kafka:kafka_2.11:2.4.0,org.apache.kafka:kafka-streams-scala_2.11:2.4.0 --class org.scalablecomputing.spark.batchjobsaverager.Main --master spark://spark-master:7077 --deploy-mode client --conf spark.app.name=batch-averager-weekly --conf spark.driver.host=spark-master --conf spark.cores.max=3 --num-executors 3 --executor-cores 1 --supervise /batchjobsaverager.jar weekly &
#sleep 1m
#kubectl exec -it $(kubectl get pod -l "app=spark-master" -o jsonpath='{.items[0].metadata.name}') -- bash ./spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5,org.apache.spark:spark-streaming_2.11:2.4.5,org.apache.spark:spark-sql_2.11:2.4.5,org.apache.spark:spark-streaming-kafka-0-10_2.11:2.4.5,com.datastax.spark:spark-cassandra-connector_2.11:2.4.3,org.apache.kafka:kafka_2.11:2.4.0,org.apache.kafka:kafka-streams-scala_2.11:2.4.0 --class org.scalablecomputing.spark.batchjobsaverager.Main --master spark://spark-master:7077 --deploy-mode client --conf spark.app.name=batch-averager-monthly --conf spark.driver.host=spark-master --conf spark.cores.max=3 --num-executors 3 --executor-cores 1 --supervise /batchjobsaverager.jar monthly &
#sleep 1m
#kubectl exec -it $(kubectl get pod -l "app=spark-master" -o jsonpath='{.items[0].metadata.name}') -- bash ./spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5,org.apache.spark:spark-streaming_2.11:2.4.5,org.apache.spark:spark-sql_2.11:2.4.5,org.apache.spark:spark-streaming-kafka-0-10_2.11:2.4.5,com.datastax.spark:spark-cassandra-connector_2.11:2.4.3,org.apache.kafka:kafka_2.11:2.4.0,org.apache.kafka:kafka-streams-scala_2.11:2.4.0 --class org.scalablecomputing.spark.batchjobsaverager.Main --master spark://spark-master:7077 --deploy-mode client --conf spark.app.name=batch-averager-all --conf spark.driver.host=spark-master --conf spark.cores.max=3 --num-executors 3 --executor-cores 1 --supervise /batchjobsaverager.jar all &
#sleep 1m

#kubectl exec -it $(kubectl get pod -l "app=spark-master" -o jsonpath='{.items[0].metadata.name}') -- bash ./spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5,org.apache.spark:spark-streaming_2.11:2.4.5,org.apache.spark:spark-sql_2.11:2.4.5,org.apache.spark:spark-streaming-kafka-0-10_2.11:2.4.5,com.datastax.spark:spark-cassandra-connector_2.11:2.4.3,org.apache.kafka:kafka_2.11:2.4.0,org.apache.kafka:kafka-streams-scala_2.11:2.4.0 --class org.scalablecomputing.spark.streamingpredictor.Main --master spark://spark-master:7077 --deploy-mode client --conf spark.app.name=streaming-prediction --conf spark.driver.host=spark-master --conf spark.cores.max=3 --num-executors 3 --executor-cores 1 --supervise /streamingpredictor.jar &